                                                                                                                                                                                                                                                                                                                                                #include<stdio.h>
                                                                                                                                                                                                                                                                                                                                                int main()
                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                    double lone_amount,interest_rate,total_year,total_amount,monthly_amount;
                                                                                                                                                                                                                                                                                                                                                    printf("Enter the lone_amount=    ");
                                                                                                                                                                                                                                                                                                                                                    scanf("%lf",&lone_amount);
                                                                                                                                                                                                                                                                                                                                                    printf("Enter the interest_rate:  ");
                                                                                                                                                                                                                                                                                                                                                    scanf("%lf",&interest_rate=  );
                                                                                                                                                                                                                                                                                                                                                    printf("Enter the total_year=  ");
                                                                                                                                                                                                                                                                                                                                                    scanf("%lf",&total_year);
                                                                                                                                                                                                                                                                                                                                                     total_amount=lone_amount + lone_amount*interest_rate/100;
                                                                                                                                                                                                                                                                                                                                                    printf("total_amount is %0.2lf\n",total_amount);
                                                                                                                                                                                                                                                                                                                                                    monthly_amount=total_amount/(12*total_year);
                                                                                                                                                                                                                                                                                                                                                    printf("monthly_amount is %0.2lf",monthly_amount);
                                                                                                                                                                                                                                                                                                                                                    return 0;
                                                                                                                                                                                                                                                                                                                                                }
